jobs:
  cla-verify:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
        GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      id: query-worksheet
      uses: jroehl/gsheet.action@release
      with:
        commands: "[\n  { \"command\": \"getData\", \"args\": { \"range\": \"'Form\
          \ Responses'!E:E\" } }\n]\n"
        spreadsheetId: ${{ secrets.GSHEET_ID }}
    - continue-on-error: true
      env:
        GITHUB_USER_NAME: ${{ github.event.pull_request.user.login }}
        RESULTS: ${{ steps.query-worksheet.outputs.results }}
      id: username-index
      name: Find username index
      run: 'index=`echo "$RESULTS" | jq -c ''.results[].result.rawData | flatten |
        index(env.GITHUB_USER_NAME)''`

        [ "$index" = "null" ] && echo "Username not found in list"

        echo "::set-output name=index::$index"

        '
      shell: bash
    - continue-on-error: true
      if: steps.username-index.outputs.index == 'null' && !contains(github.event.pull_request.labels.*.name,
        'CLA')
      name: Add CLA Label and Comment
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "github.issues.createComment({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  body: 'Hi ${{\
          \ github.event.pull_request.user.login }},\\n\\nWelcome to ControlsFX and\
          \ thank you for taking time to contribute to this project.\\n\\nWe do not\
          \ recognise you as a contributor. Can you please sign ControlsFX Individual\
          \ Contributor Agreement: https://cla.controlsfx.org ?'\n})\ngithub.issues.addLabels({\n\
          \  issue_number: context.issue.number,\n  owner: context.repo.owner,\n \
          \ repo: context.repo.repo,\n  labels: ['CLA']\n})\n"
    - continue-on-error: true
      if: steps.username-index.outputs.index != 'null' && !contains(github.event.pull_request.labels.*.name,
        'CLA-VERIFIED')
      name: Add CLA-VERIFIED Label
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "github.issues.addLabels({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  labels: ['CLA-VERIFIED']\n\
          })\n"
    - continue-on-error: true
      if: steps.username-index.outputs.index != 'null' && contains(github.event.pull_request.labels.*.name,
        'CLA')
      name: Remove CLA Label
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "github.issues.removeLabel({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  name: 'CLA'\n\
          })"
name: CLA verification
on:
  repository_dispatch:
    types: trigger-ga___cla.yml
